import React, { useState } from 'react'
import { useNavigate } from 'react-router'

// Components
import { FormField } from '../components'
// utils
import { getRandomPrompt } from '../utils'
// Assets
import preview from '../assets/assets/preview.png'

const CreatePost = () => {
  const navigate = useNavigate()

  const [form, setForm] = useState({
    name: '',
    prompt: '',
    photo: ''
  })

  const [generatingImg, setGeneratingImg] = useState(false)
  const [loading, setLoading] = useState(false)

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault()
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {

  }

  const handleSurpriseMe = () => {

  }

  return (
    <section className='max-w-7x1 mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          The Community Showcase
        </h1>
        <p className='mt-2 text-[#666e75] text-[16px] max-w-[500px]'>
          Browse trough a collection of imaginative and visually stunning images generated by DELL-E AI and share them with the community
        </p>
      </div>

      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField
            labelName="Your name"
            type="text"
            name="name"
            placeholder="Jonh Doe"
            value={form.name}
            handleChange={handleChange}
          />
          <FormField
            labelName="Your name"
            type="text"
            name="name"
            placeholder="a pencil and watercolor drawing of a bright city in the future with flying cars"
            value={form.prompt}
            handleChange={handleChange}
            isSurprisedMe
            handleSurpriseMe={handleSurpriseMe}
          />

          <div className='relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 h-64 p-3 flex justify-center items-center'>
            {
              form.photo ? (
                <img
                  src={form.photo}
                  alt={form.photo}
                  className='w-full h-full object-contain'
                />
              ) : (
                <img
                  src={preview}
                  alt="preview"
                  className='w-9/12 h-9/12 object-contain opacity-40'
                />
              )
            }
          </div>
        </div>
      </form>
    </section>
  )
}

export default CreatePost
